format_version: 3
pipelines:
  - name: PythonAppPipeline
    group: MyApplicationGroup
    label_template: '${COUNT}'

    materials:
      - git: https://github.com/your-username/your-python-app.git
        branch: main

    stages:
      - name: Build
        jobs:
          - name: BuildJob
            tasks:
              - exec:
                  command: python
                  arguments: ['build.py']
                working_directory: /path/to/your/app

      - name: Test
        jobs:
          - name: TestJob
            tasks:
              - exec:
                  command: python
                  arguments: ['test.py']
                working_directory: /path/to/your/app

      - name: Deploy
        jobs:
          - name: DeployJob
            tasks:
              - exec:
                  command: python
                  arguments: ['deploy.py']
                working_directory: /path/to/your/app
