pipeline:
  name: Your-Go-App-Pipeline

stages:
  - name: Build
    jobs:
      - name: Build-App
        resources:
          - your-build-agent
        environment_variables:
          - name: GOPATH
            value: /go
        tasks:
          - script:
              - mkdir -p /go/src/github.com/yourusername/your-go-app
              - cp -r ./* /go/src/github.com/yourusername/your-go-app/
              - cd /go/src/github.com/yourusername/your-go-app
              - go build -o your-go-app

  - name: Test
    jobs:
      - name: Test-App
        resources:
          - your-test-agent
        environment_variables:
          - name: GOPATH
            value: /go
        tasks:
          - script:
              - cd /go/src/github.com/yourusername/your-go-app
              - go test ./...

  - name: Deploy
    jobs:
      - name: Deploy-App
        resources:
          - your-deploy-agent
        environment_variables:
          - name: GOPATH
            value: /go
        tasks:
          - script:
              - # Add your deployment script here
